# Helm Chart Deployment
#
# This file deploys the demo Helm chart to the AKS cluster.

# Generate random MCP API key for authentication
resource "random_password" "mcp_api_key" {
  length  = 32
  special = false
}

# Get AKS admin credentials
data "azapi_resource_action" "aks_creds" {
  type        = "Microsoft.ContainerService/managedClusters@2025-07-02-preview"
  resource_id = azapi_resource.aks.id
  action      = "listClusterAdminCredential"
  method      = "POST"

  response_export_values = ["kubeconfigs"]
}

# Get OpenAI API key
data "azurerm_cognitive_account" "ai_services" {
  name                = azurerm_cognitive_account.ai_services.name
  resource_group_name = azurerm_resource_group.main.name
}

locals {
  # The kubeconfig is base64-encoded YAML, we need to decode and parse it
  kubeconfig_raw = base64decode(data.azapi_resource_action.aks_creds.output.kubeconfigs[0].value)
  kubeconfig     = yamldecode(local.kubeconfig_raw)

  # OpenAI configuration
  openai_endpoint = azurerm_cognitive_account.ai_services.endpoint
  openai_base_url = "${local.openai_endpoint}openai/v1/"

  # Node resource group follows Azure's naming convention: MC_<rg>_<cluster>_<location>
  node_resource_group = "MC_${azurerm_resource_group.main.name}_${azapi_resource.aks.name}_${azurerm_resource_group.main.location}"
}

# Configure Helm provider to use AKS credentials
provider "helm" {
  kubernetes {
    host                   = local.kubeconfig.clusters[0].cluster.server
    client_certificate     = base64decode(local.kubeconfig.users[0].user["client-certificate-data"])
    client_key             = base64decode(local.kubeconfig.users[0].user["client-key-data"])
    cluster_ca_certificate = base64decode(local.kubeconfig.clusters[0].cluster["certificate-authority-data"])
  }
}

# Deploy demo microservices chart
resource "helm_release" "demo" {
  name      = "demo"
  chart     = "${path.module}/../../charts/demo"
  namespace = "default"

  # Override registry from Terraform state
  set {
    name  = "registry"
    value = azurerm_container_registry.main.login_server
  }

  # MCP API key
  set_sensitive {
    name  = "mcpApiKey"
    value = random_password.mcp_api_key.result
  }

  # OpenAI configuration
  set_sensitive {
    name  = "openai.apiKey"
    value = data.azurerm_cognitive_account.ai_services.primary_access_key
  }

  set {
    name  = "openai.baseUrl"
    value = local.openai_base_url
  }

  # Chef agent MCP URL (uses static IP)
  set {
    name  = "chefAgent.mcpUrl"
    value = "http://${azurerm_public_ip.mcp_chef_services.ip_address}/mcp"
  }

  # Static IP configuration
  set {
    name  = "staticIPResourceGroup"
    value = azurerm_resource_group.main.name
  }

  set {
    name  = "staticIPNames.mcpChefServices"
    value = azurerm_public_ip.mcp_chef_services.name
  }

  set {
    name  = "staticIPNames.mcpPublicFarmerTools"
    value = azurerm_public_ip.mcp_public_farmer_tools.name
  }

  set {
    name  = "staticIPNames.mcpVisualizationGenerator"
    value = azurerm_public_ip.mcp_visualization_generator.name
  }

  # Wait for AKS to be ready, ACR permissions, and static IPs to be created
  depends_on = [
    azapi_resource.aks,
    azurerm_role_assignment.aks_acr_pull,
    azurerm_cognitive_account.ai_services,
    azurerm_public_ip.mcp_chef_services,
    azurerm_public_ip.mcp_public_farmer_tools,
    azurerm_public_ip.mcp_visualization_generator
  ]
}

# Output for verification
output "helm_demo_status" {
  description = "Status of the demo Helm release"
  value = {
    name      = helm_release.demo.name
    namespace = helm_release.demo.namespace
    version   = helm_release.demo.version
    status    = helm_release.demo.status
  }
}

output "mcp_api_key" {
  description = "MCP API key for authentication (sensitive)"
  value       = random_password.mcp_api_key.result
  sensitive   = true
}

# Generate .env file for tests with service IPs and credentials
resource "local_file" "test_env" {
  filename = "${path.module}/../tests/.env"
  content  = <<-EOT
    # Service IPs for deployed services
    # Automatically generated by Terraform
    # DO NOT EDIT MANUALLY - Changes will be overwritten

    # MCP API Key for authentication
    MCP_API_KEY=${random_password.mcp_api_key.result}

    # Service IPs (LoadBalancer external IPs)
    MCP_VISUALIZATION_IP=${azurerm_public_ip.mcp_visualization_generator.ip_address}
    MCP_PUBLIC_FARMER_IP=${azurerm_public_ip.mcp_public_farmer_tools.ip_address}
    MCP_CHEF_SERVICES_IP=${azurerm_public_ip.mcp_chef_services.ip_address}

    # API Services (ClusterIP - for internal access only)
    # Note: API Stock is internal only, use kubectl port-forward to access
    API_STOCK_IP=10.0.0.1
  EOT

  # Only create after deployment is complete
  depends_on = [
    helm_release.demo
  ]
}

output "test_env_file" {
  description = "Path to generated .env file for tests"
  value       = local_file.test_env.filename
}
