# Deploy demo microservices chart
resource "helm_release" "demo" {
  name      = "demo"
  chart     = "${path.module}/../../charts/demo"
  namespace = "default"

  # Override registry from Terraform state
  set {
    name  = "registry"
    value = azurerm_container_registry.main.login_server
  }

  # Domain configuration
  set {
    name  = "domain"
    value = var.domain
  }

  # MCP API key
  set_sensitive {
    name  = "mcpApiKey"
    value = random_password.mcp_api_key.result
  }

  # OpenAI configuration
  set_sensitive {
    name  = "openai.apiKey"
    value = data.azurerm_cognitive_account.ai_services.primary_access_key
  }

  set {
    name  = "openai.baseUrl"
    value = local.openai_base_url
  }

  # PostgreSQL configuration (Azure Database for PostgreSQL Flexible Server)
  set {
    name  = "postgres.host"
    value = azurerm_postgresql_flexible_server.main.fqdn
  }

  set {
    name  = "postgres.port"
    value = "5432"
  }

  set {
    name  = "postgres.database"
    value = azurerm_postgresql_flexible_server_database.main.name
  }

  set {
    name  = "postgres.username"
    value = azurerm_postgresql_flexible_server.main.administrator_login
  }

  set_sensitive {
    name  = "postgres.password"
    value = azurerm_postgresql_flexible_server.main.administrator_password
  }

  set {
    name  = "postgres.jdbcUrl"
    value = "jdbc:postgresql://${azurerm_postgresql_flexible_server.main.fqdn}:5432/${azurerm_postgresql_flexible_server_database.main.name}"
  }

  # Keycloak configuration
  set_sensitive {
    name  = "keycloak.adminPassword"
    value = random_password.keycloak_admin.result
  }

  set {
    name  = "keycloak.hostname"
    value = "keycloak.${var.domain}"
  }

  # Tavily API key (you'll need to provide this)
  set_sensitive {
    name  = "tavily.apiKey"
    value = var.tavily_api_key
  }

  # Chef agent MCP URL (now via ingress)
  set {
    name  = "chefAgent.mcpUrl"
    value = "https://mcp-chef-services.${var.domain}/mcp"
  }

  # Dreamfarm agent URLs (now via ingress)
  set {
    name  = "dreamfarmAgent.farmerToolsUrl"
    value = "https://mcp-public-farmer-tools.${var.domain}/mcp"
  }

  set {
    name  = "dreamfarmAgent.visualizationUrl"
    value = "https://mcp-visualization-generator.${var.domain}/mcp"
  }

  set {
    name  = "dreamfarmAgent.keycloakUrl"
    value = "https://keycloak.${var.domain}"
  }

  # Frontend configuration (now via ingress)
  set {
    name  = "frontend.backendUrl"
    value = "https://dreamfarm-agent.${var.domain}"
  }

  set {
    name  = "frontend.keycloakUrl"
    value = "https://keycloak.${var.domain}"
  }

  set {
    name  = "frontend.redirectUri"
    value = "https://${var.domain}/"
  }

  # Wait for AKS, ACR permissions, cert-manager, and nginx ingress
  depends_on = [
    azapi_resource.aks,
    azurerm_role_assignment.aks_acr_pull,
    azurerm_cognitive_account.ai_services,
    azurerm_postgresql_flexible_server.main,
    helm_release.nginx_ingress,
    time_sleep.wait_for_cert_manager
  ]
}

# Output for verification
output "helm_demo_status" {
  description = "Status of the demo Helm release"
  value = {
    name      = helm_release.demo.name
    namespace = helm_release.demo.namespace
    version   = helm_release.demo.version
    status    = helm_release.demo.status
  }
}

output "mcp_api_key" {
  description = "MCP API key for authentication (sensitive)"
  value       = random_password.mcp_api_key.result
  sensitive   = true
}

# Generate .env file for tests with service URLs and credentials
resource "local_file" "test_env" {
  filename = "${path.module}/../tests/.env"
  content  = <<-EOT
    # Service URLs for deployed services
    # Automatically generated by Terraform
    # DO NOT EDIT MANUALLY - Changes will be overwritten

    # MCP API Key for authentication
    MCP_API_KEY=${random_password.mcp_api_key.result}

    # OpenAI Configuration
    OPENAI_API_KEY=${data.azurerm_cognitive_account.ai_services.primary_access_key}
    OPENAI_BASE_URL=${local.openai_base_url}

    # PostgreSQL Configuration (Azure Database for PostgreSQL)
    POSTGRES_HOST=${azurerm_postgresql_flexible_server.main.fqdn}
    POSTGRES_PORT=5432
    POSTGRES_DATABASE=${azurerm_postgresql_flexible_server_database.main.name}
    POSTGRES_USER=${azurerm_postgresql_flexible_server.main.administrator_login}
    POSTGRES_PASSWORD=${azurerm_postgresql_flexible_server.main.administrator_password}

    # Keycloak Configuration
    KEYCLOAK_ADMIN_PASSWORD=${random_password.keycloak_admin.result}
    KEYCLOAK_URL=https://keycloak.${var.domain}

    # Tavily API Key
    TAVILY_API_KEY=${var.tavily_api_key}

    # Service URLs (via Ingress with HTTPS)
    MCP_CHEF_SERVICES_URL=https://mcp-chef-services.${var.domain}/mcp
    MCP_PUBLIC_FARMER_URL=https://mcp-public-farmer-tools.${var.domain}/mcp
    MCP_VISUALIZATION_URL=https://mcp-visualization-generator.${var.domain}/mcp
    DREAMFARM_AGENT_URL=https://dreamfarm-agent.${var.domain}
    KEYCLOAK_URL=https://keycloak.${var.domain}
    FRONTEND_URL=https://${var.domain}

    # Ingress FQDN (for DNS configuration)
    INGRESS_FQDN=${azurerm_public_ip.ingress.fqdn}
    
    # Domain configuration
    DOMAIN=${var.domain}

    # API Services (ClusterIP - for internal access only)
    # Note: API Stock and Chef Agent are internal only, use kubectl port-forward to access
    # API_STOCK_URL=http://api-stock
    # CHEF_AGENT_URL=http://chef-agent
  EOT

  # Only create after deployment is complete
  depends_on = [
    helm_release.demo
  ]
}

output "test_env_file" {
  description = "Path to generated .env file for tests"
  value       = local_file.test_env.filename
}
