# Tests Configuration Management
# 
# This file manages the .env file for the smoke tests.
# It provides the BASE_URL and MCP_API_KEY for testing deployed services.
# Note: Service IPs are assigned dynamically by Azure Load Balancer after deployment.

locals {
  tests_dir     = "${path.module}/../tests"
  env_file_path = "${local.tests_dir}/.env"
}

# Generate the .env file content
# Note: Individual service IPs must be retrieved after LoadBalancer services are created
locals {
  env_content = <<-EOT
# Service URLs for deployed services
# Automatically generated by Terraform - do not edit manually
# Note: Retrieve actual LoadBalancer IPs using: kubectl get svc -o wide

# MCP API Key for authentication
# This key is required to access MCP services
MCP_API_KEY=${random_password.mcp_api_key.result}

# Instructions:
# After deployment, get service IPs with:
# kubectl get svc mcp-chef-services -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
# kubectl get svc mcp-public-farmer-tools -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
# kubectl get svc mcp-visualization-generator -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
# kubectl get svc api-stock -o jsonpath='{.spec.clusterIP}'
EOT
}

# Write the .env file
resource "local_file" "tests_env" {
  content         = local.env_content
  filename        = local.env_file_path
  file_permission = "0600"  # Restrictive permissions since it contains sensitive data

  # Ensure parent directory exists
  directory_permission = "0755"

  # Only create after all dependencies are ready
  depends_on = [
    random_password.mcp_api_key,
    helm_release.demo
  ]
}

# Output for verification
output "tests_env_path" {
  description = "Path to the tests .env file"
  value       = local.env_file_path
}

output "tests_config_status" {
  description = "Status of the tests configuration"
  value = {
    env_file_created = true
    has_mcp_api_key  = true
    note             = "Retrieve LoadBalancer IPs after deployment using kubectl get svc"
  }
}
