"""Import concept embeddings parquet into concept_embeddings table.

Reads processed/concept_embeddings.parquet generated by embeddings_concepts.py
and inserts/updates rows in concept_embeddings (vector(2000)).

Usage:
  uv run python data/scripts/import_concept_embeddings.py
  uv run python data/scripts/import_concept_embeddings.py --truncate

Env:
  PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD

Assumptions:
  - DDL (06_create_concept_embeddings.sql) already applied.
  - Embedding column is list[float] length 2000.
"""
from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path
from typing import List

import pandas as pd
import psycopg2
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

EMBED_DIM = 2000


def _conn():
    load_dotenv()
    return psycopg2.connect(
        host=os.getenv('PGHOST', 'localhost'),
        port=int(os.getenv('PGPORT', 5432)),
        database=os.getenv('PGDATABASE', 'aidb'),
        user=os.getenv('PGUSER', 'admin'),
        password=os.getenv('PGPASSWORD', 'Admin12345678'),
    )


def _validate(df: pd.DataFrame) -> None:
    required = {"concept_type", "concept_id", "name", "description", "normalized_text", "embedding"}
    if not required.issubset(df.columns):
        raise ValueError(f'Missing columns: {required - set(df.columns)}')
    # Basic dimension check on first non-null embedding
    for emb in df['embedding']:
        if emb is None:
            continue
        if len(emb) != EMBED_DIM:
            raise ValueError(f'Unexpected embedding dimension {len(emb)} != {EMBED_DIM}')
        break


def _to_pgvector(values: List[float]) -> str:
    return '[' + ','.join(f'{v:.6f}' for v in values) + ']'


def import_parquet(path: Path, truncate: bool) -> bool:
    if not path.exists():
        raise FileNotFoundError(path)
    df = pd.read_parquet(path)
    _validate(df)
    logger.info('Loaded %d concept embedding rows from %s', len(df), path)
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute("SELECT 1 FROM information_schema.tables WHERE table_name='concept_embeddings'")
        if cur.fetchone() is None:
            raise RuntimeError('concept_embeddings table not found; run DDL first')
        if truncate:
            logger.warning('Truncating concept_embeddings (dev reset)')
            cur.execute('TRUNCATE concept_embeddings')
        sql = (
            "INSERT INTO concept_embeddings (concept_type, concept_id, name, description, normalized_text, embedding) "
            "VALUES (%s,%s,%s,%s,%s,%s) ON CONFLICT (concept_type, concept_id) DO UPDATE SET "
            "name=EXCLUDED.name, description=EXCLUDED.description, normalized_text=EXCLUDED.normalized_text, "
            "embedding=EXCLUDED.embedding, updated_at=NOW()"
        )
        rows = [(
            r.concept_type,
            r.concept_id,
            r.name,
            r.description,
            r.normalized_text,
            _to_pgvector(r.embedding),
        ) for r in df.itertuples(index=False)]
        cur.executemany(sql, rows)
        conn.commit()
        logger.info('Imported %d rows into concept_embeddings', len(rows))
        return True
    except Exception:
        conn.rollback()
        logger.exception('Failed importing concept embeddings')
        return False
    finally:
        cur.close()
        conn.close()


def main() -> bool:
    parser = argparse.ArgumentParser(description='Import concept embeddings parquet into DB.')
    parser.add_argument('--truncate', action='store_true', help='Truncate table before import (dev only).')
    args = parser.parse_args()
    base_dir = Path(__file__).parent
    parquet_path = (base_dir / '../processed/concept_embeddings.parquet').resolve()
    return import_parquet(parquet_path, args.truncate)


if __name__ == '__main__':  # pragma: no cover
    raise SystemExit(0 if main() else 1)
