{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
  {{- if .external }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "{{ $.Values.loadBalancerResourceGroup }}"
  {{- end }}
spec:
  type: {{ if .external }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}