apiVersion: v1
kind: Service
metadata:
  name: mcp-public-farmer-tools
  labels:
    app: mcp-public-farmer-tools
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.staticIPResourceGroup | quote }}
    service.beta.kubernetes.io/azure-pip-name: {{ .Values.staticIPNames.mcpPublicFarmerTools | quote }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: mcp-public-farmer-tools
